### ISSUE TITLE
PYFFTW error when running fbp

### ISSUE THREAD

**Issue by bgris** [odlgroup/odl#1002]
ODL version : '0.5.4.dev0'
numpy version : '1.12.1'
pyfftw version : '0.10.3.dev0+e827cb5'
Ran file : filtered_backprojection_parallel_3d.py

Error message : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bgris/miniconda3/envs/odl/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/home/bgris/miniconda3/envs/odl/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/bgris/odl/examples/tomo/filtered_backprojection_parallel_3d.py", line 51, in <module>
    fbp_reconstruction = fbp(proj_data)
  File "/home/bgris/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/bgris/odl/odl/operator/operator.py", line 1310, in _call
    return self.left(self.right(x))
  File "/home/bgris/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/bgris/odl/odl/operator/operator.py", line 1310, in _call
    return self.left(self.right(x))
  File "/home/bgris/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/bgris/odl/odl/operator/operator.py", line 1310, in _call
    return self.left(self.right(x))
  File "/home/bgris/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/bgris/odl/odl/operator/operator.py", line 62, in _default_call_out_of_place
    op._call_in_place(x, out, **kwargs)
  File "/home/bgris/odl/odl/trafos/fourier.py", line 890, in _call
    out[:] = self._call_pyfftw(x.asarray(), out.asarray(), **kwargs)
  File "/home/bgris/odl/odl/trafos/fourier.py", line 1360, in _call_pyfftw
    axes=self.axes, normalise_idft=False, **kwargs)
  File "/home/bgris/odl/odl/trafos/backends/pyfftw_bindings.py", line 209, in pyfftw_call
    threads=threads, axes=axes)
  File "pyfftw/pyfftw.pyx", line 1112, in pyfftw.pyfftw.FFTW.__cinit__ (/tmp/pip-build-m68y7qdb/pyfftw/pyfftw/pyfftw.c:10585)
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

```

**Comment by kohr-h** [comment]
I've seen this before. Can you try pyFFTW 0.10.4 using `pip install pyfftw`?

**Comment by adler-j** [comment]
Any update on this, have you tried pyFFTW 0.10.4? 

If it works, perhaps we should make it a requirement?

**Comment by adler-j** [comment]
Could use an update on this, don't want bugs like this hanging around.

**Comment by bgris** [comment]
I'll try to look at it today, but i'm not sure how. And I have a problem with my computer : commits do not work i do not know why.

________________________________

**Comment by bgris** [comment]
I have now the version of pyFFTW is 0.10.4 and the file  filtered_backprojection_parallel_3d.py is running.

**Comment by adler-j** [comment]
I'll update our pyfftw requirement then
