### ISSUE TITLE
 After ODL installation, in Spyder opening a new ipython console session error

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#1178]
After `odl` installation, when opening a new ipython console session or restarting ipython kernel within Spyder, it crashes. Below is the error message. But if I try `python3` on the command line,  then run corresponding error-happened commands as those in Spyder, it works well. I use the same python interpreter (python3) in the same path for both.

Run `python3` on the command line
```
(odl-py35) chench@chench:~$ python3
Python 3.5.4 |Anaconda, Inc.| (default, Oct  5 2017, 08:00:22) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import namedtuple
>>> from collections import ChainMap as _ChainMap
>>> exit()

```
Error message:
```python
An error ocurred while starting the kernel
Failed to import the site module
Error processing line 1 of /home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/matplotlib.0.2‑py3.5‑nspkg.pth:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 167, in addpackage
exec(line)
File "", line 1, in 
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/types.py", line 166, in 
import functools as _functools
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/functools.py", line 21, in 
from collections import namedtuple
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 26, in 
import sys, os, time, io, traceback, warnings, weakref, collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 5, in 
import linecache
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/linecache.py", line 11, in 
import tokenize
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/tokenize.py", line 98, in 
class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):
AttributeError: module 'collections' has no attribute 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 559, in 
main()
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 541, in main
known_paths = addsitepackages(known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 318, in addsitepackages
addsitedir(sitedir, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 206, in addsitedir
addpackage(sitedir, name, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 177, in addpackage
import traceback
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 3, in 
import collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 28, in 
from string import Template
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/string.py", line 53, in 
from collections import ChainMap as _ChainMap
ImportError: cannot import name 'ChainMap'
Failed to import the site module
Error processing line 1 of /home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/matplotlib𔂬.0.2‑py3.5‑nspkg.pth:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 167, in addpackage
exec(line)
File "", line 1, in 
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/types.py", line 166, in 
import functools as _functools
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/functools.py", line 21, in 
from collections import namedtuple
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 26, in 
import sys, os, time, io, traceback, warnings, weakref, collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 5, in 
import linecache
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/linecache.py", line 11, in 
import tokenize
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/tokenize.py", line 98, in 
class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):
AttributeError: module 'collections' has no attribute 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 559, in 
main()
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 541, in main
known_paths = addsitepackages(known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 318, in addsitepackages
addsitedir(sitedir, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 206, in addsitedir
addpackage(sitedir, name, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 177, in addpackage
import traceback
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 3, in 
import collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 28, in 
from string import Template
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/string.py", line 53, in 
from collections import ChainMap as _ChainMap
ImportError: cannot import name 'ChainMap'
Failed to import the site module
Error processing line 1 of /home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/matplotlib𔂬.0.2‑py3.5‑nspkg.pth:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 167, in addpackage
exec(line)
File "", line 1, in 
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/types.py", line 166, in 
import functools as _functools
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/functools.py", line 21, in 
from collections import namedtuple
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 26, in 
import sys, os, time, io, traceback, warnings, weakref, collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 5, in 
import linecache
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/linecache.py", line 11, in 
import tokenize
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/tokenize.py", line 98, in 
class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):
AttributeError: module 'collections' has no attribute 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 559, in 
main()
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 541, in main
known_paths = addsitepackages(known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 318, in addsitepackages
addsitedir(sitedir, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 206, in addsitedir
addpackage(sitedir, name, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 177, in addpackage
import traceback
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 3, in 
import collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 28, in 
from string import Template
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/string.py", line 53, in 
from collections import ChainMap as _ChainMap
ImportError: cannot import name 'ChainMap'
Failed to import the site module
Error processing line 1 of /home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/matplotlib𔂬.0.2‑py3.5‑nspkg.pth:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 167, in addpackage
exec(line)
File "", line 1, in 
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/types.py", line 166, in 
import functools as _functools
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/functools.py", line 21, in 
from collections import namedtuple
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 26, in 
import sys, os, time, io, traceback, warnings, weakref, collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 5, in 
import linecache
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/linecache.py", line 11, in 
import tokenize
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/tokenize.py", line 98, in 
class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):
AttributeError: module 'collections' has no attribute 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 559, in 
main()
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 541, in main
known_paths = addsitepackages(known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 318, in addsitepackages
addsitedir(sitedir, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 206, in addsitedir
addpackage(sitedir, name, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 177, in addpackage
import traceback
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 3, in 
import collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 28, in 
from string import Template
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/string.py", line 53, in 
from collections import ChainMap as _ChainMap
ImportError: cannot import name 'ChainMap'
Failed to import the site module
Error processing line 1 of /home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/matplotlib𔂬.0.2‑py3.5‑nspkg.pth:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 167, in addpackage
exec(line)
File "", line 1, in 
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/types.py", line 166, in 
import functools as _functools
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/functools.py", line 21, in 
from collections import namedtuple
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 26, in 
import sys, os, time, io, traceback, warnings, weakref, collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 5, in 
import linecache
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/linecache.py", line 11, in 
import tokenize
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/tokenize.py", line 98, in 
class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):
AttributeError: module 'collections' has no attribute 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 559, in 
main()
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 541, in main
known_paths = addsitepackages(known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 318, in addsitepackages
addsitedir(sitedir, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 206, in addsitedir
addpackage(sitedir, name, known_paths)
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site.py", line 177, in addpackage
import traceback
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/traceback.py", line 3, in 
import collections
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/collections/__init__.py", line 26, in 
from operator import itemgetter as _itemgetter, eq as _eq
File "/home/chench/odl/odl/operator/__init__.py", line 24, in 
from .operator import *
File "/home/chench/odl/odl/operator/operator.py", line 22, in 
from future import standard_library
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/site‑packages/future/standard_library/__init__.py", line 64, in 
import logging
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/logging/__init__.py", line 28, in 
from string import Template
File "/home/chench/miniconda2/envs/odl‑py35/lib/python3.5/string.py", line 53, in 
from collections import ChainMap as _ChainMap
ImportError: cannot import name 'ChainMap'
```

**Comment by adler-j** [comment]
So what is happening here is that `odl.operator` is "stealing" the `operator` package (https://docs.python.org/library/operator.html).

This should in general *not* be happening, and the only reason I can image for it happening is that you are trying to run spyder from insde `/home/chench/odl/odl/`, which would give `odl.operator` priority. Are you doing this?

**Comment by chongchenmath** [comment]
Yes. But it is enforced. I cannot change path '/home/chench/odl/odl/' via PYTHONPATH manager. How to fix it?

**Comment by adler-j** [comment]
Perhaps you started Spyder from the `home/chench/odl/odl/` folder? Try exiting Spyder and starting it from somewhere else?

**Comment by chongchenmath** [comment]
Thanks a lot @adler-j  I try to start spyder from home/chench/odl/. It works.

**Comment by adler-j** [comment]
Great to see this resolved, closing.
