### ISSUE TITLE
(partial) Fourier transform on spaces of shape (1, ...)

### ISSUE THREAD

**Issue by zickert** [odlgroup/odl#1206]
```
import odl
space = odl.uniform_discr([-1, -1], [1, 1], (1, 512))
ft_op = odl.trafos.FourierTransform(space, axis=1)
```
gives 
```

/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/util/ft_utils.py:120: RuntimeWarning: divide by zero encountered in true_divide
  rmin[shifted] = -np.pi / stride[shifted]
/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/util/ft_utils.py:124: RuntimeWarning: divide by zero encountered in true_divide
  2 * np.pi / (stride[shifted] * shape[shifted]))
/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/util/ft_utils.py:124: RuntimeWarning: invalid value encountered in subtract
  2 * np.pi / (stride[shifted] * shape[shifted]))
Traceback (most recent call last):

  File "<ipython-input-3-537938e28a7f>", line 1, in <module>
    ft_op = odl.trafos.FourierTransform(space, axis=1)

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/fourier.py", line 1240, in __init__
    inverse=False, domain=domain, range=range, impl=impl, **kwargs)

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/fourier.py", line 847, in __init__
    shift=self.shifts)

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/util/ft_utils.py", line 626, in reciprocal_space
    halfcomplex=halfcomplex, axes=axes)

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/trafos/util/ft_utils.py", line 151, in reciprocal_grid
    return uniform_grid(rmin, rmax, rshape)

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/discr/grid.py", line 1228, in uniform_grid
    return uniform_grid_fromintv(IntervalProd(min_pt, max_pt), shape,

  File "/afs/kth.se/home/z/i/zickert/git/odl/odl/set/domain.py", line 71, in __init__
    raise ValueError('in axis {}: max_pt is NaN'.format(axis))

ValueError: in axis 0: max_pt is NaN
```

**Comment by kohr-h** [comment]
PR made to fix this issue. Note also that the argument is `axes`, not `axis`. The name follows the `pyfftw` naming, but perhaps we should change it to `axis` as Numpy uses it.
What do you like more?

**Comment by adler-j** [comment]
We should follow numpy like slaves here, recommend a renaming.

**Comment by kohr-h** [comment]
Alright. I'll make it part of the same PR.
