### ISSUE TITLE
Public properties in `__init__`

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1260]
It turns out to be a bit dangerous to use public properties in `__init__`. The following example is a condensed version of our setup with `TensorSpace` (`A`), `NumpyTensorSpace` (`B`) and `DiscreteLp` (`C`):
```python
class A(object):
    def __init__(self, x):
        self.__x = x
        if self.x == 1:  # using public property here
            print('something')
        else:
            print('nothing')
    
    @property
    def x(self):
        return self.__x


class B(A):
    def __init__(self, x):
        super(B, self).__init__(x)


class C(A):
    def __init__(self, x):
        super(C, self).__init__(x)  # subclassing pattern
        self.b = B(x)  # composition pattern
        
    @property
    def x(self):
        return (self.b.x, 1)  # some random change of the parent property
```
If you now try to create an instance of `C`, it will fail:
```python
>>> c = C(1)
Traceback (most recent call last):

  File "<ipython-input-18-d9e82960096c>", line 1, in <module>
    c = C(1)

  File "<ipython-input-17-b1f5d3aedc99>", line 21, in __init__
    super(C, self).__init__(x)  # subclassing pattern

  File "<ipython-input-17-b1f5d3aedc99>", line 4, in __init__
    if self.x == 1:  # using public property here

  File "<ipython-input-17-b1f5d3aedc99>", line 26, in x
    return (self.b.x, 1)  # some random change of the parent property

AttributeError: 'C' object has no attribute 'b'
```
The issue is that (naturally) `C` first calls the parent initializer, which looks at the property `self.x`, but this one is **not** `A.x` but `C.x`. And since `C` is not finished yet and has no `b` attribute yet, the call fails as shown above.

### Solution
Initializers should not use a public property **unless** the intention is to allow subclasses to change the meaning of the call. If the intention is "use my own property", the private one should be used.

### Suggestion
IMO we should migrate the code from using public properties in `__init__` to private ones if in doubt. This issue is a ticking time bomb that can surface whenever a subclass changes behavior.

**Comment by adler-j** [comment]
Very reasonable point you make. We should indeed to this migration. My suggestion is however that we do it on a "as needed basis", unless you feel compelled to do a proper cleanup for this?

**Comment by kohr-h** [comment]
Yeah, I'm fine with doing it incrementally. At least we have this as reference, so whenever it surfaces again we know and can explain what's going on.
