### ISSUE TITLE
Functional translation does not convert stepsizes given as lists or array

### ISSUE THREAD

**Issue by sbanert** [odlgroup/odl#1279]
The following code crashes:
```
import odl
import numpy as np

space = odl.rn(2)
functional = odl.solvers.L2NormSquared(space)
x = space.one()
stepsize = space.element([0.5, 2.0])
stepsize_list = [0.5, 2.0]
stepsize_array = np.asarray([0.5, 2.0])
y = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize)(x)
y_list = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize_list)(x)
y_array = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize_array)(x)
```
both for the calculation of y_list and y_array. The code works fine without ".translated".

**Comment by adler-j** [comment]
The error messages are:

```
Traceback (most recent call last):

  File "<ipython-input-1-6777289be4b3>", line 11, in <module>
    y_list = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize_list)(x)

  File "e:\github\odl\odl\solvers\nonsmooth\proximal_operators.py", line 383, in quadratic_perturbation_prox_factory
    const = 1.0 / np.sqrt(sigma * 2.0 * a + 1)

TypeError: can't multiply sequence by non-int of type 'float'

Traceback (most recent call last):

  File "<ipython-input-1-6777289be4b3>", line 11, in <module>
    y_list = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize_list)(x)

  File "e:\github\odl\odl\solvers\nonsmooth\proximal_operators.py", line 383, in quadratic_perturbation_prox_factory
    const = 1.0 / np.sqrt(sigma * 2.0 * a + 1)

TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by sbanert** [comment]
If both "list" lines are deleted, the error message is different:

```python
Traceback (most recent call last):

  File "<ipython-input-1-a405cae3e522>", line 1, in <module>
    runfile('[...]/.config/spyder-py3/temp.py', wdir='[...]/.config/spyder-py3')

  File "[...]/miniconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "[...]/miniconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "[...]/.config/spyder-py3/temp.py", line 19, in <module>
    y_array = functional.translated([0.5, 0.5]).convex_conj.proximal(stepsize_array)(x)

  File "[...]/odl/odl/solvers/nonsmooth/proximal_operators.py", line 386, in quadratic_perturbation_prox_factory
    return (const * prox *

TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'OperatorComp'
```

**Comment by leftaroundabout** [comment]
@sbanert sorry to ping this old issue, but we've running into this changeset while generalizing the ODL proximals from the everything-numpy status quo to arbitrary ArrayAPI backends.

I find it quite confusing to talk about lists as step sizes, and tend to say we should not allow this at all but require the user to be more explicit. Passing an ODL-element as the `sigma` value seems reasonable, and that is (if I understand correctly) what want to also happen for a list input. (Even then I'd say it shouldn't be called "step size" anymore!)

But if a plain list is given it becomes ambiguous as an element of what space it should be interpreted (which is in the future also important to decide on which backend/device to store the data). Was there any concrete reason why you wanted to support this particular use case? After all, there are many places in ODL where you need to pass an element of a well-specified space and a list isn't accepted - even if the list could be used as the argument to `.element` of this space, which is what I'd require the user to do explicitly so it's clear what they actually want to happen.
