### ISSUE TITLE
Implementation of SART in ODL

### ISSUE THREAD

**Issue by ginsanity15** [odlgroup/odl#1316]
Is there an elegant approach to build SART (Simultaneous Algebraic Reconstruction Technique) in ODL? I haven't found any function inside ODL that is suitable to perform back-projection after each projection angle. The only clumsy solution I came up with is to create a new geometry at the beginning of each iteration (please refer to the code below). It seems to work, but creating a new geometry inside the loop doesn't sound like a good idea to me. 
Thanks for your attention, I am looking forward to hear some better suggestions from you.

```python
import odl
import numpy as np

# --- Set up the forward operator (ray transform) --- #
reco_space = odl.uniform_discr(
    min_pt=[-0.2, -0.2], max_pt=[0.2, 0.2], shape=[200, 200])

num_proj = 400
angle_partition = odl.uniform_partition(0, 2*np.pi, num_proj)

detector_partition = odl.uniform_partition(min_pt = -0.3, max_pt = 0.3, shape = 500)

geometry = odl.tomo.Parallel2dGeometry(
        angle_partition, detector_partition, src_radius=2.5, det_radius=92.5)

# Create the forward operator
ray_trafo = odl.tomo.RayTransform(reco_space, geometry)

phantom = odl.phantom.shepp_logan(reco_space, modified=True)
# Create projection data by calling the ray transform on the phantom
sinogram = ray_trafo(phantom)
sino = sinogram.asarray()

# Initialize the reconstruction image
x = reco_space.zero()

# Relaxation factor
lambda1 = 1

iteration = 10
# subiteration equals the number of projections
subiteration = num_proj
angle_step = 2*np.pi/num_proj

# Access order of the projection
selection = np.arange(subiteration)
out = np.random.permutation(selection)
# Here we perform a monochromatic SART reconstruction as check point
for i in range(iteration):
    for j in range(subiteration):
        print('Currently in subiteration %d of total iteration %d'%(j+1,i+1))
        # Operator for backprojection at this specific subiteration
        angle_partition = odl.uniform_partition(angle_step*(out[j]), angle_step*(out[j]+1), 1)
        geometry = odl.tomo.Parallel2dGeometry(
                angle_partition, detector_partition, src_radius=2.5, det_radius=92.5)
        ray_trafo_1 = odl.tomo.RayTransform(reco_space, geometry)
        # Correction at this projection angle
        norm_diff = (sino[out[j],:] - ray_trafo_1(x))/ray_trafo_1(ray_trafo_1.domain.one())
        # Get rid of abnormal point (inf, nan), which is unavoidable at edges of detector
        diff_arr = norm_diff.asarray()
        diff_arr[np.isinf(diff_arr)] = 0
        diff_arr[np.isnan(diff_arr)] = 0
        den = ray_trafo_1.range.element(diff_arr)
        diff_proj = ray_trafo_1.adjoint(den)
        x += lambda1 * diff_proj

phantom.show(title = 'Original Phantom')
x.show(title = 'SART Reconstruction')

**Comment by adler-j** [comment]
SART is conveniently implemented using `odl.solvers.kaczmarz`, which also includes various other special cases.

To use it, you need to create all the operators (one per angle, if that's what you want) but doing so should be done a-priori.

A simple implementation would look something like this:

```python
import odl
import numpy as np

# --- Set up the forward operator (ray transform) --- #
reco_space = odl.uniform_discr(
    min_pt=[-0.2, -0.2], max_pt=[0.2, 0.2], shape=[200, 200])

num_proj = 400
angle_partition = odl.uniform_partition(0, 2*np.pi, num_proj)

detector_partition = odl.uniform_partition(min_pt = -0.3, max_pt = 0.3, shape = 500)

geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)

# Create the forward operator using indexing of geometry
ray_trafos = [odl.tomo.RayTransform(reco_space, geometry[i:i+1])
              for i in range(num_proj)]

# Create sinogram for each forward operator
phantom = odl.phantom.shepp_logan(reco_space, modified=True)
sinograms = [rt(phantom) for rt in ray_trafos]

# Initialize the reconstruction image
x = reco_space.zero()

# Solve with Kaczmarz
# niter is "iteration" and omega is "lambda1"
odl.solvers.kaczmarz(ray_trafos, x, sinograms, niter=10, omega=1)

phantom.show(title = 'Original Phantom')
x.show(title = 'SART Reconstruction')
```

If you also want to include the normalization by 1/A(1), you should change the operators to include this.

**Comment by ginsanity15** [comment]
Thanks for your help, the result of this implementation is way better than the one I did.

**Comment by ginsanity15** [comment]
Thanks for your help, the result of this implementation is way better than the one I did.
I have a further question on your implementation. Is that possible for us to define geometry with 
`ray_trafos = [odl.tomo.RayTransform(reco_space, geometry[i:i+1]) for i in range(num_proj)]`
I tried to do so just now, but it returned a type error as follow:

Traceback (most recent call last):
File "<ipython-input-85-e35e93f7dad9>", line 2, in <module>
for i in range(num_proj)]
File "<ipython-input-85-e35e93f7dad9>", line 2, in <listcomp>
for i in range(num_proj)]
TypeError: 'Parallel2dGeometry' object is not subscriptable

**Comment by adler-j** [comment]
To do subscripting of geometrier you need to use the absolute latest ODL, available here in GitHub.

You can install it by 

```
pip install https://github.com/odlgroup/odl/archive/master.zip
```

**Comment by ginsanity15** [comment]
Alright thanks for sharing the link, I will take a look at it later. 👍
