### ISSUE TITLE
TGV tomography example does not work.

### ISSUE THREAD

**Issue by sbanert** [odlgroup/odl#1408]
When I run `pdhg_tomography_tgv.py` (current master branch) in Spyder, I get the following error message:
```
In [1]: runfile('[…]/odl/examples/solvers/pdhg_tomography_tgv.py', wdir='[…]/odl/examples/solvers')

<Figure size 432x288 with 0 Axes> [Phantom]
<Figure size 432x288 with 0 Axes> [Simulated data (Sinogram)]
Traceback (most recent call last):

[Some Spyder-specific messages]

  File "[…]/odl/examples/solvers/pdhg_tomography_tgv.py", line 126, in <module>
    callback=callback)

  File "[…]/odl/odl/solvers/nonsmooth/primal_dual_hybrid_gradient.py", line 193, in pdhg
    ''.format(f.domain, L.domain))

TypeError: `f.domain` ProductSpace(
    uniform_discr([  0.    , -28.2843], [  3.1416,  28.2843], (223, 143), dtype='float32'),
    ProductSpace(uniform_discr([-20., -20.], [ 20.,  20.], (100, 100), dtype='float32'), 2),
    ProductSpace(uniform_discr([-20., -20.], [ 20.,  20.], (100, 100), dtype='float32'), 4)
) must equal `op.domain` ProductSpace(
    uniform_discr([-20., -20.], [ 20.,  20.], (100, 100), dtype='float32'),
    ProductSpace(uniform_discr([-20., -20.], [ 20.,  20.], (100, 100), dtype='float32'), 2)
)
```

**Comment by jaweriaamjad** [comment]
was this issue resolved? I am getting the same error
