### ISSUE TITLE
a problem of project on l1-ball operator

### ISSUE THREAD

**Issue by dlutgy** [odlgroup/odl#1590]
Hello, recently I want to call the Proj_l1 operator in "odl.solvers.nonsmooth.proximal_operators.proj_l1" but return the following error:

> Traceback (most recent call last):
  File "c:\Users\13292\Desktop\master2\CT\code_1118\call_alg1.py", line 63, in <module>
    f, Energy, Image_distance, g_real, g_noise, SSIM, PSNR = proposed_alg1(N_theta=N_theta, N_s=N_s, min_pt=min_pt, max_pt=max_pt, shape=shape, noise_level=noise_level, split='1')
  File "c:\Users\13292\Desktop\master2\CT\code_1118\proposed_alg1.py", line 86, in proposed_alg1
    ProjL1 = odl.solvers.nonsmooth.proximal_operators.proj_l1(vspace,sigma*gamma)
  File "C:\Users\13292\AppData\Roaming\Python\Python37\site-packages\odl\solvers\nonsmooth\proximal_operators.py", line 1543, in proj_l1
    out = x.space.element()
AttributeError: 'ProductSpace' object has no attribute 'space'

Here is the source code in odl:
`if out is None:
        out = x.space.element()

    u = x.ufuncs.absolute()
    v = x.ufuncs.sign()
    proj_simplex(u, radius, out)
    out *= v`
In the document of this method, which says the first parameter x denotes space. I did so but return an error. Do you know what is going wrong? And how can I call the Proj_l1 operator in odl?

**Comment by adler-j** [comment]
Hi! Could you give a minimal example which is runnable so we can reproduce the error?

**Comment by dlutgy** [comment]
OK，here is a minimal example:
` import odl
 import numpy

 reco_space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[128, 128], dtype='float32')
 gradient = odl.Gradient(domain=reco_space)
 r = 1
 vspace = odl.ProductSpace(gradient.range,2)
 Proj_l1 = odl.solvers.nonsmooth.proj_l1(vspace,r)

 v = vspace.element()
 v = Proj_l1(v)`

**Comment by adler-j** [comment]
The function `` is a function, not a class so you need to directly call it, e.g. like this

```
import odl
import numpy

reco_space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[128, 128], dtype='float32')
gradient = odl.Gradient(domain=reco_space)
r = 1
vspace = odl.ProductSpace(gradient.range,2)

v = vspace.zero()
v = odl.solvers.nonsmooth.proj_l1(v, r)
```
