### ISSUE TITLE
IndexError in prod_space[1:] for length 1 -> Chambolle-Pock broken in 1D

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#301]
The following code gives an `IndexError`:
```python
>>> r2 = odl.Rn(2)
>>> prod_space = odl.ProductSpace(r2)
>>> prod_space[1:]
Traceback (most recent call last):
    ...

  File "/home/hkohr/Work/Projects/2015/LCR/odl/odl/set/pspace.py", line 425, in __getitem__
    return ProductSpace(*self.spaces[indices])

  File "/home/hkohr/Work/Projects/2015/LCR/odl/odl/set/pspace.py", line 202, in __init__
    super().__init__(spaces[0].field)

IndexError: tuple index out of range
```
This is in contrast to python lists, tuples and Numpy arrays which give an empty set. Maybe we don't want to handle empty products, but then we get errors in places like [this](https://github.com/odlgroup/odl/blob/b58bad8311319a22c4a708068c2d66a4a3cc8a8a/odl/solvers/advanced/proximal_operators.py#L347) instead of a silently ignored iteration. The net effect is now that we cannot run Chambolle-Pock on 1d examples.

**Comment by kohr-h** [comment]
Addition: running
```python
>>> odl.ProductSpace()
```
has the same effect and raises the same exception. The error message could be better.

**Comment by kohr-h** [comment]
Looking good.
