### ISSUE TITLE
ProxImaL example in documentation fails

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#651]
The doctest-like example for the ProxImaL bindings guide gives the following error:
```
**********************************************************************
File "/home/hkohr/git/odl/doc/source/guide/in_depth/proximal_lang_guide.rst", line 19, in proximal_lang_guide.rst
Failed example:
    prob.solve()
Exception raised:
    Traceback (most recent call last):
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest proximal_lang_guide.rst[6]>", line 1, in <module>
        prob.solve()
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/algorithms/problem.py", line 136, in solve
        *args, **kwargs)
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/algorithms/pock_chambolle.py", line 123, in solve
        K.adjoint(y, KTy)
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/lin_ops/comp_graph.py", line 157, in adjoint
        self.traverse_graph(adjoint_eval, False)
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/lin_ops/comp_graph.py", line 177, in traverse_graph
        node_fn(curr)
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/lin_ops/comp_graph.py", line 153, in adjoint_eval
        node.adjoint(outputs, inputs)
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/site-packages/proximal/lin_ops/grad.py", line 106, in adjoint
        fj = f[..., j]
    IndexError: index 1 is out of bounds for axis 1 with size 1
**********************************************************************
```
I'm on `proximal` version 0.1.4.

**Comment by kohr-h** [comment]
Further down in the same file:
```
**********************************************************************
File "/home/hkohr/git/odl/doc/source/guide/in_depth/proximal_lang_guide.rst", line 50, in proximal_lang_guide.rst
Failed example:
    space = odl.ProductSpace(odl.rn(3), odl.cn(2))
Exception raised:
    Traceback (most recent call last):
      File "/home/hkohr/miniconda/envs/odl-py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest proximal_lang_guide.rst[10]>", line 1, in <module>
        space = odl.ProductSpace(odl.rn(3), odl.cn(2))
      File "/home/hkohr/git/odl/odl/space/pspace.py", line 258, in __init__
        raise ValueError('all spaces must have the same field')
    ValueError: all spaces must have the same field
**********************************************************************
```

**Comment by adler-j** [comment]
I installed proximal from the github and the first one worked for me, second will be fixed.

You need [this change](https://github.com/comp-imaging/ProxImaL/pull/20/files) to run the example and there is no way for us to test this atm. I was hoping for a new proximal release soonish.
