### ISSUE TITLE
Error in show when using upper boundary for coords

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#675]
Minimal example:

``` python
>>> space = odl.uniform_discr([0, 0], [1, 1], [10, 10])
>>> x = space.one()
>>> x.show(coords=[1, None])
Traceback (most recent call last):

  File "<ipython-input-6-8b47643bf30d>", line 1, in <module>
    x.show(coords=[1, 1])

  File "/home/hkohr/git/odl/odl/discr/lp_discr.py", line 856, in show
    part = self.space.partition[indices].squeeze()

  File "/home/hkohr/git/odl/odl/discr/partition.py", line 451, in __getitem__
    int_to_slice=True)

  File "/home/hkohr/git/odl/odl/util/normalize.py", line 257, in normalized_index_expression
    ''.format(idx, i, n))

IndexError: Index 10 is out of bounds for axis 0 with size 10.
```

**Comment by adler-j** [comment]
This could be fixed by using the `index_of` thing I implemented recently.
