### ISSUE TITLE
Version 0.5.3 seems broken

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#869]
I have installed `odl` version 0.5.3 using `pip`, and I get the following error
```
>>> import odl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/__init__.py", line 36, in <module>
    from .discr import *
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/discr/__init__.py", line 36, in <module>
    from .lp_discr import *
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/discr/lp_discr.py", line 39, in <module>
    from odl.util import (
ImportError: cannot import name 'safe_int_conv'
```
The problem is that `safe_int_conv` is not exposed in `__all__` in `odl/util/normalize.py`. However, changing adding this I get a second error
```
>>> import odl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/__init__.py", line 48, in <module>
    from . import solvers
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/solvers/__init__.py", line 23, in <module>
    from .functional import *
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/solvers/functional/__init__.py", line 25, in <module>
    from .default_functionals import *
  File "/home/aringh/miniconda3/envs/my_test_env/lib/python3.6/site-packages/odl/solvers/functional/default_functionals.py", line 32, in <module>
    from odl.operator import (Operator, ConstantOperator, ZeroOperator,
ImportError: cannot import name 'PointwiseNorm'
```
I stopped here, so I don't know how many of these seemingly broken imports there are. But it looks like `odl` does not work out-of-the-box after a pip-install.

In order to double check this, I have created a clean conda environment, and I have reproduced these erros in this environment. What I have done is: 1) create a new conda environment, 2) install `pip` in it with `conda install pip`, and 3) install `odl` using `pip install odl`. Nothing more, nothing less. After that I have the following packages
```
(my_test_env) aringh@gelfand:~$ conda list
# packages in environment at /home/aringh/miniconda3/envs/my_test_env:
#
future                    0.16.0                    <pip>
numpy                     1.12.0                    <pip>
odl                       0.5.3                     <pip>
openssl                   1.0.2k                        0  
pip                       9.0.1                    py36_1  
python                    3.6.0                         0  
readline                  6.2                           2  
scipy                     0.18.1                    <pip>
setuptools                27.2.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```
and the python version is 3.6:
```
(my_test_env) aringh@gelfand:~$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
```

**Comment by kohr-h** [comment]
That's weird because at the [commit tagged in the release](https://github.com/odlgroup/odl/commit/0a8b6ef22166acb4e647d505d89f737cd77bbe08) `safe_int_conv` is in `__all__`. Seems like the PyPI package is based on a different tag. I'll have to investigate and make a new packages asap.

Seems like we need a well-define release process (and let Travis test it).

**Comment by kohr-h** [comment]
Can you check again with the latest package version (0.5.3.post2)?

There are two known issues, though:
- For Python 3.6 a doctest fails, see #874
- For Numpy 1.12, another doctest fails, see #873

Other than that I hope the new packages work.

**Comment by aringh** [comment]
I'm running on another computer, but it is also running ubuntu. It seems to work :-)

I have the following packages:
```
(test_env) [...]$ conda list
# packages in environment at [...]/miniconda3/envs/test_env:
#
cycler                    0.10.0                   py35_0  
dbus                      1.10.10                       0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
future                    0.16.0                   py35_1  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
matplotlib                2.0.0               np111py35_0  
nomkl                     1.0                           0  
numpy                     1.11.3             py35_nomkl_0  [nomkl]
odl                       0.5.3.post2               <pip>
openblas                  0.2.19                        0  
openssl                   1.0.2k                        0  
pcre                      8.39                          1  
pip                       9.0.1                    py35_1  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_2  
python                    3.5.2                         0  
python-dateutil           2.6.0                    py35_0  
pytz                      2016.10                  py35_0  
qt                        5.6.2                         3  
readline                  6.2                           2  
scipy                     0.18.1          np111py35_nomkl_1  [nomkl]
setuptools                27.2.0                   py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3
```

**Comment by kohr-h** [comment]
Okay, nice. Someone should also try the windows conda builds since I slightly changed the `meta.yaml` file in the dependencies section.

**Comment by adler-j** [comment]
Except a bunch of other issues (#873 and #875), it seems to be working well.

**Comment by adler-j** [comment]
Can we close this now?

**Comment by kohr-h** [comment]
The issue seems to be solved, so yes.
