### ISSUE TITLE
Read mrc file

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#892]
We use the ``FileReaderMRC`` to read mrc file following the example in ``examples/tomo/data/mrc_io.py``. Just read the given file ``test.mrc``, no problem. But if we read the interesting mrc file, get the following error:

>Traceback (most recent call last):

>  File "<ipython-input-6-8bf8cb54b126>", line 1, in <module>
>    runfile('/home/chchen/odl/odl/deform/read_mrc_data.py', wdir='/home/chchen/odl/odl/deform')

>  File "/home/chchen/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line > 866, in runfile
>    execfile(filename, namespace)

>  File "/home/chchen/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line > 94, in execfile
>   builtins.execfile(filename, *where)

>  File "/home/chchen/odl/odl/deform/read_mrc_data.py", line 114, in <module>
>    header, data = reader.read()

>  File "/home/chchen/odl/odl/tomo/data/uncompr_bin.py", line 385, in read
>    return self.read_header(), self.read_data()

>  File "/home/chchen/odl/odl/tomo/data/mrc.py", line 632, in read_data
>    order='F')

>ValueError: total size of new array must be unchanged
> > > >

**Comment by adler-j** [comment]
What is "the interesting mrc file"? Can you provide it?

**Comment by chongchenmath** [comment]
Already sent to your email address.

**Comment by adler-j** [comment]
I get another error:

MWE:

```python
from odl.tomo.data import FileReaderMRC

with FileReaderMRC('tiltseries_nonoise.mrc') as reader:
    header, data = reader.read()
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/seadljon/Desktop/tmp/load.py", line 11, in <module>
    header, data = reader.read()
  File "c:\programming\odl\odl\tomo\data\uncompr_bin.py", line 385, in read
    return self.read_header(), self.read_data()
  File "c:\programming\odl\odl\tomo\data\mrc.py", line 631, in read_data
    data = super().read_data(dstart, dend).reshape(self.data_shape,
  File "c:\programming\odl\odl\tomo\data\uncompr_bin.py", line 535, in read_data
    self.data_dtype))
ValueError: trying to read 9760122 bytes, which is not a multiple of the itemsize 4 of the data type float32
```

Perhaps there is an error with the data?

**Comment by adler-j** [comment]
Followup question, can the file be read by some other reader. Also I guess we need @kohr-h input on this since I have absolutely no idea about how this file format works.

**Comment by adler-j** [comment]
Further clues that the data is bad is that another mrc reader also fails

```python
import mrcfile

with mrcfile.open(file_path) as mrc:
    print(mrc)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/seadljon/Desktop/tmp/load.py", line 30, in <module>
    with mrcfile.open(file_path) as mrc:
  File "C:\Anaconda\lib\site-packages\mrcfile\__init__.py", line 140, in open
    raise orig_err
ValueError: Unrecognised machine stamp: 0x44 0x11 0x00 0x00
```

**Comment by kohr-h** [comment]
Probably the header is wrong. You can do
```python
with FileReaderMRC('tiltseries_nonoise.mrc') as reader:
    header = reader.read_header()
```
Then look at the following values
- `header.header_size` 
- `header.extended_header_size`
- 9760122 minus the sum of the above, see if you can get any idea of what is going wrong

**Comment by kohr-h** [comment]
Also look at the header as a whole and check if the values make any sense at all:
```python
for key, value in header.items():
    print(key, ':', value)
```

**Comment by adler-j** [comment]
```
('nx', ':', {'description': 'Number of columns', 'value': array([200]), 'offset': 0})
('ny', ':', {'description': 'Number of rows', 'value': array([200]), 'offset': 4})
('nz', ':', {'description': 'Number of sections', 'value': array([61]), 'offset': 8})
('mode', ':', {'description': 'Data type', 'value': array([2]), 'offset': 12})
('mx', ':', {'description': 'Number of intervals along X of the "unit cell"', 'value': array([200]), 'offset': 28})
('my', ':', {'description': 'Number of intervals along Y of the "unit cell"', 'value': array([200]), 'offset': 32})
('mz', ':', {'description': 'Number of intervals along Z of the "unit cell"', 'value': array([61]), 'offset': 36})
('cella', ':', {'description': 'Cell dimension in angstroms (whole volume)', 'value': array([ 1280.       ,  1280.       ,   390.3999939], dtype=float32), 'offset': 40})
('mapc', ':', {'description': 'axis corresponding to columns (1,2,3 for X,Y,Z)', 'value': array([1]), 'offset': 64})
('mapr', ':', {'description': 'axis corresponding to rows (1,2,3 for X,Y,Z)', 'value': array([2]), 'offset': 68})
('maps', ':', {'description': 'axis corresponding to sections (1,2,3 for X,Y,Z)', 'value': array([3]), 'offset': 72})
('dmin', ':', {'description': 'Minimum density value', 'value': array([ 1875.37927246], dtype=float32), 'offset': 76})
('dmax', ':', {'description': 'Maximum density value', 'value': array([ 2473.05493164], dtype=float32), 'offset': 80})
('dmean', ':', {'description': 'Mean density value', 'value': array([ 2218.34204102], dtype=float32), 'offset': 84})
('ispg', ':', {'description': 'Space group number 0, 1, or 401', 'value': array([0]), 'offset': 88})
('nsymbt', ':', {'description': 'Number of bytes in extended header', 'value': array([122]), 'offset': 92})
('exttype', ':', {'description': 'Extended header type', 'value': array([' ', ' ', ' ', ' '], 
      dtype='|S1'), 'offset': 104})
('nversion', ':', {'description': 'Format version identification number', 'value': array([0]), 'offset': 108})
('origin', ':', {'description': 'Origin in X, Y, Z used in transform', 'value': array([0, 0, 0]), 'offset': 196})
('map', ':', {'description': "Character string 'MAP' to identify file type", 'value': array(['M', 'A', 'P', ' '], 
      dtype='|S1'), 'offset': 208})
('machst', ':', {'description': 'Machine stamp', 'value': array(['D', '\x11', ' ', ' '], 
      dtype='|S1'), 'offset': 212})
('rms', ':', {'description': 'RMS deviation of map from mean density', 'value': array([ 0.], dtype=float32), 'offset': 216})
('nlabl', ':', {'description': 'Number of labels being used', 'value': array([2]), 'offset': 220})
('label', ':', {'description': '10 80-character text labels', 'value': array([['C', 'r', 'e', 'a', 't', 'e', 'd', ' ', 'b', 'y', ' ', 'T', 'E',
        'M', '-', 's', 'i', 'm', 'u', 'l', 'a', 't', 'o', 'r', ',', ' ',
        'v', 'e', 'r', 's', 'i', 'o', 'n', ' ', '1', '.', '4', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'T', 'i', 'l',
        't', ' ', 'a', 'x', 'i', 's', ' ', 'r', 'o', 't', 'a', 't', 'i',
        'o', 'n', ' ', 'a', 'n', 'g', 'l', 'e', ' ', '=', ' ', '-', '9',
        '0', '.', '0', '0', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ']], 
      dtype='|S1'), 'offset': 224})

```

**Comment by adler-j** [comment]
Header size:

```
>>> reader.header_size
1024
>>> reader.extended_header_size
122
```

**Comment by kohr-h** [comment]
Hm, 
```python
>>> (9760122 - 122) / 4
2440000.0
>>> 200 * 200 * 61
2440000
```
Should match. Seems like the extended header is not treated properly.

**Comment by adler-j** [comment]
Extended header is buggy or something

```python
>>> extended_header = reader.read_extended_header()
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/seadljon/Desktop/tmp/load.py", line 16, in <module>
    extended_header = reader.read_extended_header()
  File "c:\programming\odl\odl\tomo\data\mrc.py", line 535, in read_extended_header
    "".format(self.extended_header_type))
ValueError: extended header type '    ' not supported
```

**Comment by kohr-h** [comment]
What's the total file size?

**Comment by kohr-h** [comment]
`header_size` is wrong, it should give the total size, i.e. 1024 + 122

**Comment by kohr-h** [comment]
Can you check `header['nsymbt']['value']`?

**Comment by kohr-h** [comment]
The total file size should be `(200 * 200 * 61) * np.dtype('float32').itemsize + 1024 + 122 = 9761146`. If it doesn't match, the file has been written out wrong.

**Comment by kohr-h** [comment]
> Extended header is buggy or something

No, the reader only supports `'FEI'` extended header format. There's basically no convention on this, so we have to pick those we want to support. No idea what kind of stuff TEM-Simulator stores there, but it also doesn't tell a proper extended header type as you see in the 
```
('exttype', ':', {'description': 'Extended header type', 'value': array([' ', ' ', ' ', ' '], 
      dtype='|S1'), 'offset': 104})
```
parameter. Just blank, and no way to support this. It should be changed to some unique label there.

**Comment by chongchenmath** [comment]
I remember I can read `tiltseries_nonoise.mrc` out based on `mrc2014.py` one month ago.

**Comment by adler-j** [comment]
> Can you check `header['nsymbt']['value']`?

```
> >>> header['nsymbt']['value']
array([122])
```
> The total file size should be `(200 * 200 * 61) * np.dtype('float32').itemsize + 1024 + 122 = 9761146`. If it doesn't match, the file has been written out wrong.

```
>>> import os
>>> os.stat('tiltseries_nonoise.mrc').st_size
9761146L
```

Anyway, the `extended_header` stuff only exist inside the MRC reader, the general readers (`FileReaderRawBinaryWithHeader`) don't know about them. How would it know to "skip" this? I.e. the start point is currently given as `dstart_abs = int(self.header_size)`. If i change this to `dstart_abs = int(self.header_size + self.extended_header_size)`, I can load the file.

I guess this is a bug with the reader.

**Comment by adler-j** [comment]
Example result with this fix, it looks reasonable no?

![figure_1](https://cloud.githubusercontent.com/assets/2202312/22692098/b20eacb6-ed3d-11e6-9189-e833e7ad6989.png)

**Comment by ozanoktem** [comment]
This looks correct.

**Comment by chongchenmath** [comment]
Correct!

**Comment by adler-j** [comment]
Pull request solving this is up.

**Comment by adler-j** [comment]
Obviously we need to add a test that uses the extended header

**Comment by adler-j** [comment]
Solved on master. Does it work for you now?

**Comment by chongchenmath** [comment]
Okay. can read normally. Thank you all!
